name: Build FishByte APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Instalacja Javy i zależności systemowych (tak jak w Colab)
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip build-essential git python3 \
            python3-dev ffmpeg libsdl2-dev libsdl2-image-dev \
            libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev \
            libswscale-dev libavformat-dev libavcodec-dev \
            zlib1g-dev libgstreamer1.0 \
            gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
            libssl-dev libffi-dev autoconf libtool automake \
            zip unzip openjdk-17-jdk

      # 2. Instalacja Buildozera i Cythona (tak jak w Colab)
      - name: Install Buildozer & Cython
        run: |
          pip3 install --upgrade pip
          pip3 install buildozer cython==0.29.36

      # 3. Budowanie (tak jak w Colab)
      - name: Build with Buildozer
        run: |
          # Czyszczenie na wszelki wypadek
          buildozer android clean
          # Budowanie z automatycznym potwierdzaniem licencji
          yes | buildozer android debug

      # 4. Wysłanie gotowego pliku
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FishByte-APK
          path: bin/*.apk
