name: Build FishByte APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # KROK 1: Instalacja tylko niezbędnych zależności (Bez Gstreamer/FFmpeg)
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip build-essential git python3 \
            python3-dev libsdl2-dev libsdl2-image-dev \
            libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev \
            zlib1g-dev libssl-dev libffi-dev \
            autoconf libtool automake \
            zip unzip openjdk-17-jdk

      # KROK 2: Instalacja Buildozera i Cythona
      - name: Install Buildozer & Cython
        run: |
          pip3 install --upgrade pip
          pip3 install buildozer cython==0.29.36

      # KROK 3: Budowanie
      - name: Build with Buildozer
        run: |
          # Czyszczenie na wszelki wypadek
          buildozer android clean
          # Budowanie
          yes | buildozer android debug

      # KROK 4: Wysyłanie pliku
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FishByte-APK
          path: bin/*.apk
