name: Build FishByte APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Instalacja zależności (Wersja lekka - bez zbędnych bibliotek wideo)
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip build-essential git python3 \
            python3-dev libsdl2-dev libsdl2-image-dev \
            libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev \
            zlib1g-dev libssl-dev libffi-dev \
            autoconf libtool automake \
            zip unzip openjdk-17-jdk

      # 2. Instalacja Buildozera i Cythona
      - name: Install Buildozer & Cython
        run: |
          pip3 install --upgrade pip
          pip3 install buildozer cython==0.29.36

      # 3. Budowanie (BEZ CLEAN - bo środowisko jest czyste)
      - name: Build with Buildozer
        run: |
          yes | buildozer android debug

      # 4. Wysłanie pliku APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FishByte-APK
          path: bin/*.apk
